services:
  postgres:
    image: postgres:18-alpine
    container_name: rpe-postgres
    environment:
      POSTGRES_USER: hmcts
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hmcts -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:8-alpine
    container_name: rpe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data: