version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hmcts-postgres
    environment:
      POSTGRES_USER: hmcts
      POSTGRES_PASSWORD: hmcts_dev_password
      POSTGRES_DB: hmcts_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hmcts"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: