apiVersion: v2
appVersion: '1.0'
description: A Helm chart for expressjs-monorepo-template
name: expressjs-monorepo-template-web
annotations:
  team: rpe
home: https://github.com/hmcts/expressjs-monorepo-template
version: 0.0.1
dependencies:
  - name: nodejs
    version: 3.2.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
