name: Security

on:
  pull_request:
    branches: [master, main]
  merge_group:
    branches: [master, main]
  push:
    branches: [master, main]
  schedule:
    - cron: '0 2 * * *'

permissions:
  # Required to upload SARIF file to CodeQL
  actions: read
  # Required to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read

jobs:
  scan:
    name: Dependency Scan
    if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'schedule' || github.event_name == 'pull_request' || github.event_name == 'merge_group'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.2.2
    with:
      scan-args: |-
        --config=.github/osv-scanner.toml
        ./