name: OSV Scanner

on:
  pull_request:
    branches: [master, main]
  merge_group:
    branches: [master, main]
  push:
    branches: [master, main]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

permissions:
  # Required to upload SARIF file to CodeQL
  actions: read
  # Required to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read

jobs:
  scan-pr:
    if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.2.2
    with:
      scan-args: |-
        --config=osv-scanner.toml
        ./

  scan-scheduled:
    if: github.event_name == 'push' || github.event_name == 'schedule'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.2.2
    with:
      scan-args: |-
        --config=osv-scanner.toml
        ./