name: Release

on:
  push:
    branches:
      - master

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: hmcts/cnp-githubactions-library/.github/workflows/npm-publish-library.yaml@feat/release-please
    with:
      node-version-file: '.nvmrc'
      build-command: 'yarn test && yarn build'
      npm-scope: '@hmcts-cft'
    secrets: inherit
